version: '3.5'

services:
  cfd-py-build:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.1.0
    environment:
      CFD_SRC: /private/cfd-python
      CFD_WORK: /private/work/cfd-python
    working_dir: /private/cfd-python
    volumes:
      - /private/work
      - .:/private/cfd-python
    working_dir: /private/cfd-python
    command: /bin/bash -c "./tools/build_for_docker.sh"

  cfd-py-integration-test:
    image: ghcr.io/ko-matsu/elements-testing:v0.0.5
    volumes:
      - ./integration_test:/root/integration_test
    working_dir: /root/integration_test
    entrypoint: /bin/bash -c "./test_entrypoint.sh"

  cfd-py-test:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.1.0
    environment:
      CFD_SRC: /private/cfd-python
      CFD_WORK: /private/work/cfd-python
    working_dir: /private/cfd-python
    volumes:
      - /private/work
      - .:/private/cfd-python
    working_dir: /private/cfd-python
    command: /bin/bash -c "./tools/build_and_test_for_docker.sh"
